# Copyright 2021, Peter Birch, mailto:peter@lightlogic.co.uk
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Guard statement
ifeq ($(__COMMON_VARS_DEFINED__),)
__COMMON_VARS_DEFINED__ := 1

# ==============================================================================
# Common Setup
# ==============================================================================

MAKE_DIRS +=
QUIET     ?= yes
PRECMD    ?= $(if $(filter yes,$(QUIET)),@,)

# ==============================================================================
# Miscellaneous
# ==============================================================================

SPACE ?=
SPACE := $(SPACE) $(SPACE)

# End of guard statement
endif # __COMMON_VARS_DEFINED__
